--- drivers/misc/Makefile
+++ drivers/misc/Makefile
@@ -49,3 +49,4 @@
 obj-$(CONFIG_USB_SWITCH_FSA9480) += fsa9480.o
 obj-$(CONFIG_ALTERA_STAPL)	+=altera-stapl/
 obj-$(CONFIG_MAX8997_MUIC)	+= max8997-muic.o
+obj-$(CONFIG_HWLAT_DETECTOR)	+= hwlat_detector.o
